// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProject.DAL;

#nullable disable

namespace MyProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251026113642_UpdateInfo1")]
    partial class UpdateInfo1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyProject.DAL.Models.AppUsers", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AdminID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AdminID");

                    b.Property<string>("MaGV")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSV")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaSV")
                        .IsUnique()
                        .HasFilter("[MaSV] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyProject.DAL.Models.Calendars", b =>
                {
                    b.Property<string>("MaMH")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaGV")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TietHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaMH", "MaGV");

                    b.HasIndex("MaGV");

                    b.ToTable("LichGiangDay");
                });

            modelBuilder.Entity("MyProject.DAL.Models.ClassRoom", b =>
                {
                    b.Property<string>("MaLop")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoLuongSV")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaKhoa");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("MyProject.DAL.Models.Faculty", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmailKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhongCongTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SoLuongLop")
                        .HasColumnType("bigint");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TruongKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("MyProject.DAL.Models.Lecturers", b =>
                {
                    b.Property<string>("MaGV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGV");

                    b.HasIndex("MaKhoa");

                    b.ToTable("GiangVien");
                });

            modelBuilder.Entity("MyProject.DAL.Models.Notify", b =>
                {
                    b.Property<string>("MaTB")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AnhURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTB");

                    b.HasIndex("Username");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("MyProject.DAL.Models.Score", b =>
                {
                    b.Property<string>("MaSV")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaMH")
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("DiemCK")
                        .HasColumnType("real");

                    b.Property<float>("DiemGK")
                        .HasColumnType("real");

                    b.Property<float>("DiemTrungBinh")
                        .HasColumnType("real");

                    b.Property<string>("HocKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSV", "MaMH");

                    b.HasIndex("MaMH");

                    b.ToTable("Diem");
                });

            modelBuilder.Entity("MyProject.DAL.Models.SoftwareInfo", b =>
                {
                    b.Property<int>("MaPM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPM"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPM");

                    b.ToTable("ThongtinPM");
                });

            modelBuilder.Entity("MyProject.DAL.Models.Students", b =>
                {
                    b.Property<string>("MaSV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSV");

                    b.HasIndex("MaLop");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("MyProject.DAL.Models.Subjects", b =>
                {
                    b.Property<string>("MaMH")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoTiet")
                        .HasColumnType("int");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenMH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaMH");

                    b.HasIndex("MaKhoa");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("MyProject.DAL.Models.AppUsers", b =>
                {
                    b.HasOne("MyProject.DAL.Models.Lecturers", "lecturers")
                        .WithMany("users")
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyProject.DAL.Models.Students", "students")
                        .WithOne("users")
                        .HasForeignKey("MyProject.DAL.Models.AppUsers", "MaSV")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("lecturers");

                    b.Navigation("students");
                });

            modelBuilder.Entity("MyProject.DAL.Models.Calendars", b =>
                {
                    b.HasOne("MyProject.DAL.Models.Lecturers", "GiangVien")
                        .WithMany("LichGiangDay")
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyProject.DAL.Models.Subjects", "MonHoc")
                        .WithMany("LichGiangDay")
                        .HasForeignKey("MaMH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("MyProject.DAL.Models.ClassRoom", b =>
                {
                    b.HasOne("MyProject.DAL.Models.Faculty", "faculty")
                        .WithMany("classrooms")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("faculty");
                });

            modelBuilder.Entity("MyProject.DAL.Models.Lecturers", b =>
                {
                    b.HasOne("MyProject.DAL.Models.Faculty", "faculty")
                        .WithMany("lecturers")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("faculty");
                });

            modelBuilder.Entity("MyProject.DAL.Models.Notify", b =>
                {
                    b.HasOne("MyProject.DAL.Models.AppUsers", "Admin")
                        .WithMany("Notifies")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("MyProject.DAL.Models.Score", b =>
                {
                    b.HasOne("MyProject.DAL.Models.Subjects", "subjects")
                        .WithMany("Scores")
                        .HasForeignKey("MaMH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyProject.DAL.Models.Students", "students")
                        .WithMany("Scores")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("students");

                    b.Navigation("subjects");
                });

            modelBuilder.Entity("MyProject.DAL.Models.Students", b =>
                {
                    b.HasOne("MyProject.DAL.Models.ClassRoom", "classrooms")
                        .WithMany("Students")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("classrooms");
                });

            modelBuilder.Entity("MyProject.DAL.Models.Subjects", b =>
                {
                    b.HasOne("MyProject.DAL.Models.Faculty", "faculty")
                        .WithMany("subjects")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("faculty");
                });

            modelBuilder.Entity("MyProject.DAL.Models.AppUsers", b =>
                {
                    b.Navigation("Notifies");
                });

            modelBuilder.Entity("MyProject.DAL.Models.ClassRoom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("MyProject.DAL.Models.Faculty", b =>
                {
                    b.Navigation("classrooms");

                    b.Navigation("lecturers");

                    b.Navigation("subjects");
                });

            modelBuilder.Entity("MyProject.DAL.Models.Lecturers", b =>
                {
                    b.Navigation("LichGiangDay");

                    b.Navigation("users");
                });

            modelBuilder.Entity("MyProject.DAL.Models.Students", b =>
                {
                    b.Navigation("Scores");

                    b.Navigation("users")
                        .IsRequired();
                });

            modelBuilder.Entity("MyProject.DAL.Models.Subjects", b =>
                {
                    b.Navigation("LichGiangDay");

                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
